<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>tripleo.elijah</groupId>
        <artifactId>elevated.parts.core-api</artifactId>
        <version>elevated-potential.l251121</version>
    </parent>

    <groupId>tripleo.elijah</groupId>
    <artifactId>elevated-potential.core.queues</artifactId>
<!--    <version>${revision}</version>-->
    <version>elevated-potential.l251121</version>

    <properties>
        <revision>elevated-potential.l251121</revision>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        <guava.version>33.5.0-jre</guava.version>
        <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>

        <truth.version>1.4.5</truth.version>
        <jspecify.version>1.0.0</jspecify.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>4.0.0-M1</version>
            <scope>test</scope>
        </dependency>

        <!--        <dependency>-->
        <!--            <groupId>org.awaitility</groupId>-->
        <!--            <artifactId>awaitility</artifactId>-->
        <!--            <version>4.3.0</version>-->
        <!--        </dependency>-->

        <!--        <dependency>-->
        <!--            <groupId>tripleo.elijah</groupId>-->
        <!--            <artifactId>elevated-potential-core-api-xxx</artifactId>-->
        <!--            <version>${revision}</version>-->
        <!--            <scope>compile</scope>-->
        <!--        </dependency>-->
        <!--        <dependency>-->
        <!--            <groupId>tripleo.elijah</groupId>-->
        <!--            <artifactId>elevated-potential-core-api</artifactId>-->
        <!--            <version>${revision}</version>-->
        <!--            <scope>compile</scope>-->
        <!--        </dependency>-->

        <dependency>
            <groupId>org.jctools</groupId>
            <artifactId>jctools-core</artifactId>
            <version>4.0.5</version>
        </dependency>

    </dependencies>

</project>