<?xml version="1.0" encoding="UTF-8"?>
<!--suppress MavenRedundantGroupId -->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

	<description>
		Zero dependencies.
		Nonsense to hold no-actual-code debug flags
	</description>

<!--
	<parent>
        <groupId>tripleo.elijah</groupId>
        <artifactId>elevated-potential</artifactId>
        <version>${revision}</version>
    </parent>
-->
	<parent>
		<groupId>tripleo.elijah</groupId>
		<artifactId>elevated.parts.core-api</artifactId>
		<version>elevated-potential.l251121</version>
	</parent>


    <groupId>tripleo.elijah</groupId>
    <artifactId>elevated-potential.s.debugflags_l251121</artifactId>
<!--    <version>${revision}</version>-->
	<version>elevated-potential.l251121</version>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<version>1.8.0</version>
				<configuration>
				</configuration>
				<executions>
					<!-- enable flattening -->
					<execution>
						<id>flatten</id>
						<phase>process-resources</phase>
						<goals>
							<goal>flatten</goal>
						</goals>
					</execution>
					<!-- ensure proper cleanup -->
					<execution>
						<id>flatten.clean</id>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
